# Funding platforms
# Uncomment and configure the platforms you want to use

# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://www.example.com/donate']
